data:
  input_streams:
    - keypoint
    - keypoint
    - rgb
    - rgb
  keypoint_file: keypoints_hrnet_dark_coco_wholebody.pkl
  use_keypoints:
    - pose
    - mouth_half
    - hand
  zip_file: WLASL.zip
  word_emb_file: wlasl_word_embeddings.pkl
  train: train.pkl
  dev: dev.pkl
  test: test.pkl
  dataset_name: WLASL-100
  num_output_frames: 64
  transform_cfg:
    img_size: 224
    color_jitter: true
    bottom_area: 0.7 #to-do
    aspect_ratio_min: 0.75
    aspect_ratio_max: 1.3
    index_setting:
      - consecutive  #train_p
      - pad  #train_m
      - central  #test_p
      - pad  #test_m
    mixup: 0.75_0.8
    from64: true
training:
  random_seed: 321
  num_workers: 8
  batch_size: 4
model:
  RecognitionNetwork:
    s3d:
      use_block: 5
      freeze_block: 0
    keypoint_s3d:
      in_channel: 0
      use_block: 5
      freeze_block: 0
    heatmap_cfg:
      raw_size:
        - 256
        - 256 #associated with name2keypoint file 
      input_size: 112
      sigma: 8
    fuse_method: four_type3
    lateral:
      pose2rgb: true
      rgb2pose: true
      variant_pose2rgb: null
      variant_rgb2pose: null
      interpolate: false
      kernel_size: 
        - 1
        - 3
        - 3
      fusion_features:
        - c1
        - c2
        - c3
        - c4
    pyramid:
      version: v1
      rgb: null
      pose: null
    visual_head:
      variant: sep_conv
      use_extra_linear: false  #for joint head only
      input_size: 1024
      hidden_size: 512  #deprecated
      ff_size: 2048  #deprecated
      pe: True  #deprecated
      ff_kernelsize:  #deprecated
        - 3
        - 3
      word_emb_dim: 300
      contras_setting: dual_ema_cosine
      topk: 100
    label_smooth: word_emb_sim_softmax_0.2_0.5
    contras_loss_weight: 1.0
    language_apply_to: rgb_keypoint_joint  #apply to which head?
